<a href="https://colab.research.google.com/github/ALexTommy1223/Mayhoc/blob/main/Lap01_20130278_H%E1%BB%93_Nh%E1%BA%ADt_Huy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Task 1.1
# Input an integer n
n = int(input("Enter the number of integers: "))

# Input n integer numbers and append them into a list L
L = []
for i in range(n):
    x = int(input("Enter integer {}: ".format(i+1)))
    L.append(x)

# Find the max/min element in L
max_element = max(L)
min_element = min(L)

# Compute the sum of elements in L
sum_elements = sum(L)

# Sort the list L in ascending order
sorted_L = sorted(L)

# Count how many positive and negative numbers are in L
positive_count = sum(1 for x in L if x > 0)
negative_count = sum(1 for x in L if x < 0)

# Display the results
print("Max element in L: ", max_element)
print("Min element in L: ", min_element)
print("Sum of elements in L: ", sum_elements)
print("Sorted list L: ", sorted_L)
print("Number of positive elements in L: ", positive_count)
print("Number of negative elements in L: ", negative_count)



Enter the number of integers: 4
Enter integer 1: 4
Enter integer 2: 1
Enter integer 3: 2
Enter integer 4: 3
Max element in L:  4
Min element in L:  1
Sum of elements in L:  10
Sorted list L:  [1, 2, 3, 4]
Number of positive elements in L:  4
Number of negative elements in L:  0


In [ ]:
# Task 1.2
n = int(input("Enter n: "))
Sn = 1.0  

for i in range(1, n+1):
    term = 1.0 / (2*i + 1) 
    Sn += term  

print("Sn =", Sn)



Enter n: 2
Sn = 1.5333333333333332


In [ ]:
# Task 1.3
from typing import List

class Product:
    def __init__(self, name: str, product_type: str, price: int, expiry_date: str):
        self.name = name
        self.product_type = product_type
        self.price = price
        self.expiry_date = expiry_date

class OrderItem:
    def __init__(self, product: Product, amount: int):
        self.product = product
        self.amount = amount

class Order:
    def __init__(self, order_id: str, customer: str, employee: str, date: str, items: List[OrderItem]):
        self.order_id = order_id
        self.customer = customer
        self.employee = employee
        self.date = date
        self.items = items

class OrderManager:
    def __init__(self, orders: List[Order]):
        self.orders = orders

    def highest_priced_product(self) -> Product:
        return max((item.product for order in self.orders for item in order.items), key=lambda p: p.price)

    def products_by_type(self) -> dict:
        product_count = {}
        for order in self.orders:
            for item in order.items:
                if item.product.product_type in product_count:
                    product_count[item.product.product_type] += item.amount
                else:
                    product_count[item.product.product_type] = item.amount
        return product_count

class ImportedProduct(Product):
    def __init__(self, name: str, product_type: str, price: int, expiry_date: str, from_country: str):
        super().__init__(name, product_type, price, expiry_date)
        self.from_country = from_country

class DomesticProduct(Product):
    pass
if __name__ == '__main__':
    product1 = Product('Apple', 'fruit', 10, '2023-03-31')
    product2 = Product('Milk', 'dairy', 20, '2023-03-05')
    product3 = ImportedProduct('Wine', 'alcohol', 50, '2023-04-30', 'France')
    product4 = DomesticProduct('Bread', 'bakery', 5, '2023-03-05')

    order1 = Order('001', 'John Doe', 'Jane Smith', '2023-03-01', [OrderItem(product1, 2), OrderItem(product2, 1)])
    order2 = Order('002', 'Jane Smith', 'John Doe', '2023-03-02', [OrderItem(product3, 1), OrderItem(product4, 3)])
    order_manager = OrderManager([order1, order2])

    print('Sản phẩm có giá trị cao nhất :', order_manager.highest_priced_product().name)
    print('Sản phẩm theo loại:', order_manager.products_by_type())



Sản phẩm có giá trị cao nhất : Wine
Sản phẩm theo loại: {'fruit': 2, 'dairy': 1, 'alcohol': 1, 'bakery': 3}


In [ ]:
# Task 2.1
import numpy as np


arr = np.arange(10, 26)
print('Mảng ban đầu:', arr)

# Reverse the array
arr = arr[::-1]
print('Mảng đảo ngược:', arr)


Mảng ban đầu: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
Mảng đảo ngược: [25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
# Task 2.2
import numpy as np


arr = np.array([1, 2, 3, 4])
print('Mảng ban đầu:', arr)


arr_2x = np.tile(arr, 2)
print('Mảng thứ hai:', arr_2x)


arr_3x = np.tile(arr, 3)
print('Mảng thứ ba:', arr_3x)


Mảng ban đầu: [1 2 3 4]
Mảng thứ hai: [1 2 3 4 1 2 3 4]
Mảng thứ ba: [1 2 3 4 1 2 3 4 1 2 3 4]


In [ ]:
# Task 2.3
import numpy as np

# Input array
arr = np.array([[0.42, 0.48, 0.32],
                [0.74, 0.58, 0.38],
                [0.51, 0.34, 0.15]])
print('Mảng ban đầu:')
print(arr)


arr[arr > 0.5] = 0.5
print('Thay thế tất cả các phần tử của mảng ban đầu bằng .5 lớn hơn .5')
print(arr)


Mảng ban đầu:
[[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]]
Thay thế tất cả các phần tử của mảng ban đầu bằng .5 lớn hơn .5
[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
